/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class CachedSupplierResponse {

    @JsonProperty("@cachedTime")
    private java.lang.String cachedtime;

    public void setCachedtime(java.lang.String cachedtime) {
        this.cachedtime = cachedtime;
    }

    public java.lang.String getCachedtime() {
        return cachedtime;
    }

    @JsonProperty("@supplierResponseTime")
    private java.lang.String supplierresponsetime;

    public void setSupplierresponsetime(java.lang.String supplierresponsetime) {
        this.supplierresponsetime = supplierresponsetime;
    }

    public java.lang.String getSupplierresponsetime() {
        return supplierresponsetime;
    }

    @JsonProperty("@matchedCurrency")
    private java.lang.String matchedcurrency;

    public void setMatchedcurrency(java.lang.String matchedcurrency) {
        this.matchedcurrency = matchedcurrency;
    }

    public java.lang.String getMatchedcurrency() {
        return matchedcurrency;
    }

    @JsonProperty("@matchedLocale")
    private java.lang.String matchedlocale;

    public void setMatchedlocale(java.lang.String matchedlocale) {
        this.matchedlocale = matchedlocale;
    }

    public java.lang.String getMatchedlocale() {
        return matchedlocale;
    }

    @JsonProperty("@supplierCacheTolerance")
    private java.lang.String suppliercachetolerance;

    public void setSuppliercachetolerance(java.lang.String suppliercachetolerance) {
        this.suppliercachetolerance = suppliercachetolerance;
    }

    public java.lang.String getSuppliercachetolerance() {
        return suppliercachetolerance;
    }

    @JsonProperty("@candidatePreptime")
    private java.lang.String candidatepreptime;

    public void setCandidatepreptime(java.lang.String candidatepreptime) {
        this.candidatepreptime = candidatepreptime;
    }

    public java.lang.String getCandidatepreptime() {
        return candidatepreptime;
    }

    @JsonProperty("@otherOverheadTime")
    private java.lang.String otheroverheadtime;

    public void setOtheroverheadtime(java.lang.String otheroverheadtime) {
        this.otheroverheadtime = otheroverheadtime;
    }

    public java.lang.String getOtheroverheadtime() {
        return otheroverheadtime;
    }

    @JsonProperty("@tpidUsed")
    private java.lang.String tpidused;

    public void setTpidused(java.lang.String tpidused) {
        this.tpidused = tpidused;
    }

    public java.lang.String getTpidused() {
        return tpidused;
    }

    @JsonProperty("@supplierResponseNum")
    private java.lang.String supplierresponsenum;

    public void setSupplierresponsenum(java.lang.String supplierresponsenum) {
        this.supplierresponsenum = supplierresponsenum;
    }

    public java.lang.String getSupplierresponsenum() {
        return supplierresponsenum;
    }

    @JsonProperty("@supplierRequestNum")
    private java.lang.String supplierrequestnum;

    public void setSupplierrequestnum(java.lang.String supplierrequestnum) {
        this.supplierrequestnum = supplierrequestnum;
    }

    public java.lang.String getSupplierrequestnum() {
        return supplierrequestnum;
    }

}