/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ChargeableRateInfo {

    @JsonProperty("NightlyRatesPerRoom")
    private NightlyRatesPerRoom nightlyratesperroom;

    public void setNightlyratesperroom(NightlyRatesPerRoom nightlyratesperroom) {
        this.nightlyratesperroom = nightlyratesperroom;
    }

    public NightlyRatesPerRoom getNightlyratesperroom() {
        return nightlyratesperroom;
    }

    @JsonProperty("Surcharges")
    private Surcharges surcharges;

    public void setSurcharges(Surcharges surcharges) {
        this.surcharges = surcharges;
    }

    public Surcharges getSurcharges() {
        return surcharges;
    }

    @JsonProperty("@commissionableUsdTotal")
    private java.lang.String commissionableusdtotal;

    public void setCommissionableusdtotal(java.lang.String commissionableusdtotal) {
        this.commissionableusdtotal = commissionableusdtotal;
    }

    public java.lang.String getCommissionableusdtotal() {
        return commissionableusdtotal;
    }

    @JsonProperty("@surchargeTotal")
    private java.lang.String surchargetotal;

    public void setSurchargetotal(java.lang.String surchargetotal) {
        this.surchargetotal = surchargetotal;
    }

    public java.lang.String getSurchargetotal() {
        return surchargetotal;
    }

    @JsonProperty("@nightlyRateTotal")
    private java.lang.String nightlyratetotal;

    public void setNightlyratetotal(java.lang.String nightlyratetotal) {
        this.nightlyratetotal = nightlyratetotal;
    }

    public java.lang.String getNightlyratetotal() {
        return nightlyratetotal;
    }

    @JsonProperty("@grossProfitOnline")
    private java.lang.String grossprofitonline;

    public void setGrossprofitonline(java.lang.String grossprofitonline) {
        this.grossprofitonline = grossprofitonline;
    }

    public java.lang.String getGrossprofitonline() {
        return grossprofitonline;
    }

    @JsonProperty("@total")
    private java.lang.String total;

    public void setTotal(java.lang.String total) {
        this.total = total;
    }

    public java.lang.String getTotal() {
        return total;
    }

    @JsonProperty("@currencyCode")
    private java.lang.String currencycode;

    public void setCurrencycode(java.lang.String currencycode) {
        this.currencycode = currencycode;
    }

    public java.lang.String getCurrencycode() {
        return currencycode;
    }

    @JsonProperty("@grossProfitOffline")
    private java.lang.String grossprofitoffline;

    public void setGrossprofitoffline(java.lang.String grossprofitoffline) {
        this.grossprofitoffline = grossprofitoffline;
    }

    public java.lang.String getGrossprofitoffline() {
        return grossprofitoffline;
    }

    @JsonProperty("@averageRate")
    private java.lang.String averagerate;

    public void setAveragerate(java.lang.String averagerate) {
        this.averagerate = averagerate;
    }

    public java.lang.String getAveragerate() {
        return averagerate;
    }

    @JsonProperty("@averageBaseRate")
    private java.lang.String averagebaserate;

    public void setAveragebaserate(java.lang.String averagebaserate) {
        this.averagebaserate = averagebaserate;
    }

    public java.lang.String getAveragebaserate() {
        return averagebaserate;
    }

    @JsonProperty("@maxNightlyRate")
    private java.lang.String maxnightlyrate;

    public void setMaxnightlyrate(java.lang.String maxnightlyrate) {
        this.maxnightlyrate = maxnightlyrate;
    }

    public java.lang.String getMaxnightlyrate() {
        return maxnightlyrate;
    }

}