/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonProperty;

public class HotelListResponse {

    @JsonProperty("HotelList")
    private HotelList hotellist;

    public void setHotellist(HotelList hotellist) {
        this.hotellist = hotellist;
    }

    public HotelList getHotellist() {
        return hotellist;
    }

    @JsonProperty("numberOfRoomsRequested")
    private java.lang.Integer numberofroomsrequested;

    public void setNumberofroomsrequested(java.lang.Integer numberofroomsrequested) {
        this.numberofroomsrequested = numberofroomsrequested;
    }

    public java.lang.Integer getNumberofroomsrequested() {
        return numberofroomsrequested;
    }

    @JsonProperty("cachedSupplierResponse")
    private CachedSupplierResponse cachedsupplierresponse;

    public void setCachedsupplierresponse(CachedSupplierResponse cachedsupplierresponse) {
        this.cachedsupplierresponse = cachedsupplierresponse;
    }

    public CachedSupplierResponse getCachedsupplierresponse() {
        return cachedsupplierresponse;
    }

    @JsonProperty("cacheKey")
    private java.lang.String cachekey;

    public void setCachekey(java.lang.String cachekey) {
        this.cachekey = cachekey;
    }

    public java.lang.String getCachekey() {
        return cachekey;
    }

    @JsonProperty("moreResultsAvailable")
    private java.lang.Boolean moreresultsavailable;

    public void setMoreresultsavailable(java.lang.Boolean moreresultsavailable) {
        this.moreresultsavailable = moreresultsavailable;
    }

    public java.lang.Boolean getMoreresultsavailable() {
        return moreresultsavailable;
    }

    @JsonProperty("customerSessionId")
    private java.lang.String customersessionid;

    public void setCustomersessionid(java.lang.String customersessionid) {
        this.customersessionid = customersessionid;
    }

    public java.lang.String getCustomersessionid() {
        return customersessionid;
    }

    @JsonProperty("cacheLocation")
    private java.lang.String cachelocation;

    public void setCachelocation(java.lang.String cachelocation) {
        this.cachelocation = cachelocation;
    }

    public java.lang.String getCachelocation() {
        return cachelocation;
    }

}