/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class HotelSummaryElement {

    @JsonProperty("RoomRateDetailsList")
    private RoomRateDetailsList roomratedetailslist;

    public void setRoomratedetailslist(RoomRateDetailsList roomratedetailslist) {
        this.roomratedetailslist = roomratedetailslist;
    }

    public RoomRateDetailsList getRoomratedetailslist() {
        return roomratedetailslist;
    }

    @JsonProperty("countryCode")
    private java.lang.String countrycode;

    public void setCountrycode(java.lang.String countrycode) {
        this.countrycode = countrycode;
    }

    public java.lang.String getCountrycode() {
        return countrycode;
    }

    @JsonProperty("tripAdvisorRatingUrl")
    private java.lang.String tripadvisorratingurl;

    public void setTripadvisorratingurl(java.lang.String tripadvisorratingurl) {
        this.tripadvisorratingurl = tripadvisorratingurl;
    }

    public java.lang.String getTripadvisorratingurl() {
        return tripadvisorratingurl;
    }

    @JsonProperty("thumbNailUrl")
    private java.lang.String thumbnailurl;

    public void setThumbnailurl(java.lang.String thumbnailurl) {
        this.thumbnailurl = thumbnailurl;
    }

    public java.lang.String getThumbnailurl() {
        return thumbnailurl;
    }

    @JsonProperty("proximityUnit")
    private java.lang.String proximityunit;

    public void setProximityunit(java.lang.String proximityunit) {
        this.proximityunit = proximityunit;
    }

    public java.lang.String getProximityunit() {
        return proximityunit;
    }

    @JsonProperty("locationDescription")
    private java.lang.String locationdescription;

    public void setLocationdescription(java.lang.String locationdescription) {
        this.locationdescription = locationdescription;
    }

    public java.lang.String getLocationdescription() {
        return locationdescription;
    }

    @JsonProperty("longitude")
    private java.lang.Double longitude;

    public void setLongitude(java.lang.Double longitude) {
        this.longitude = longitude;
    }

    public java.lang.Double getLongitude() {
        return longitude;
    }

    @JsonProperty("deepLink")
    private java.lang.String deeplink;

    public void setDeeplink(java.lang.String deeplink) {
        this.deeplink = deeplink;
    }

    public java.lang.String getDeeplink() {
        return deeplink;
    }

    @JsonProperty("amenityMask")
    private java.lang.Integer amenitymask;

    public void setAmenitymask(java.lang.Integer amenitymask) {
        this.amenitymask = amenitymask;
    }

    public java.lang.Integer getAmenitymask() {
        return amenitymask;
    }

    @JsonProperty("tripAdvisorRating")
    private java.lang.Integer tripadvisorrating;

    public void setTripadvisorrating(java.lang.Integer tripadvisorrating) {
        this.tripadvisorrating = tripadvisorrating;
    }

    public java.lang.Integer getTripadvisorrating() {
        return tripadvisorrating;
    }

    @JsonProperty("supplierType")
    private java.lang.String suppliertype;

    public void setSuppliertype(java.lang.String suppliertype) {
        this.suppliertype = suppliertype;
    }

    public java.lang.String getSuppliertype() {
        return suppliertype;
    }

    @JsonProperty("shortDescription")
    private java.lang.String shortdescription;

    public void setShortdescription(java.lang.String shortdescription) {
        this.shortdescription = shortdescription;
    }

    public java.lang.String getShortdescription() {
        return shortdescription;
    }

    @JsonProperty("stateProvinceCode")
    private java.lang.String stateprovincecode;

    public void setStateprovincecode(java.lang.String stateprovincecode) {
        this.stateprovincecode = stateprovincecode;
    }

    public java.lang.String getStateprovincecode() {
        return stateprovincecode;
    }

    @JsonProperty("airportCode")
    private java.lang.String airportcode;

    public void setAirportcode(java.lang.String airportcode) {
        this.airportcode = airportcode;
    }

    public java.lang.String getAirportcode() {
        return airportcode;
    }

    @JsonProperty("highRate")
    private java.lang.Integer highrate;

    public void setHighrate(java.lang.Integer highrate) {
        this.highrate = highrate;
    }

    public java.lang.Integer getHighrate() {
        return highrate;
    }

    @JsonProperty("address1")
    private java.lang.String address1;

    public void setAddress1(java.lang.String address1) {
        this.address1 = address1;
    }

    public java.lang.String getAddress1() {
        return address1;
    }

    @JsonProperty("hotelId")
    private java.lang.Integer hotelid;

    public void setHotelid(java.lang.Integer hotelid) {
        this.hotelid = hotelid;
    }

    public java.lang.Integer getHotelid() {
        return hotelid;
    }

    @JsonProperty("@ubsScore")
    private java.lang.String ubsscore;

    public void setUbsscore(java.lang.String ubsscore) {
        this.ubsscore = ubsscore;
    }

    public java.lang.String getUbsscore() {
        return ubsscore;
    }

    @JsonProperty("lowRate")
    private java.lang.Double lowrate;

    public void setLowrate(java.lang.Double lowrate) {
        this.lowrate = lowrate;
    }

    public java.lang.Double getLowrate() {
        return lowrate;
    }

    @JsonProperty("city")
    private java.lang.String city;

    public void setCity(java.lang.String city) {
        this.city = city;
    }

    public java.lang.String getCity() {
        return city;
    }

    @JsonProperty("tripAdvisorReviewCount")
    private java.lang.Integer tripadvisorreviewcount;

    public void setTripadvisorreviewcount(java.lang.Integer tripadvisorreviewcount) {
        this.tripadvisorreviewcount = tripadvisorreviewcount;
    }

    public java.lang.Integer getTripadvisorreviewcount() {
        return tripadvisorreviewcount;
    }

    @JsonProperty("latitude")
    private java.lang.Double latitude;

    public void setLatitude(java.lang.Double latitude) {
        this.latitude = latitude;
    }

    public java.lang.Double getLatitude() {
        return latitude;
    }

    @JsonProperty("rateCurrencyCode")
    private java.lang.String ratecurrencycode;

    public void setRatecurrencycode(java.lang.String ratecurrencycode) {
        this.ratecurrencycode = ratecurrencycode;
    }

    public java.lang.String getRatecurrencycode() {
        return ratecurrencycode;
    }

    @JsonProperty("hotelRating")
    private java.lang.Integer hotelrating;

    public void setHotelrating(java.lang.Integer hotelrating) {
        this.hotelrating = hotelrating;
    }

    public java.lang.Integer getHotelrating() {
        return hotelrating;
    }

    @JsonProperty("proximityDistance")
    private java.lang.Double proximitydistance;

    public void setProximitydistance(java.lang.Double proximitydistance) {
        this.proximitydistance = proximitydistance;
    }

    public java.lang.Double getProximitydistance() {
        return proximitydistance;
    }

    @JsonProperty("hotelInDestination")
    private java.lang.Boolean hotelindestination;

    public void setHotelindestination(java.lang.Boolean hotelindestination) {
        this.hotelindestination = hotelindestination;
    }

    public java.lang.Boolean getHotelindestination() {
        return hotelindestination;
    }

    @JsonProperty("confidenceRating")
    private java.lang.Integer confidencerating;

    public void setConfidencerating(java.lang.Integer confidencerating) {
        this.confidencerating = confidencerating;
    }

    public java.lang.Integer getConfidencerating() {
        return confidencerating;
    }

    @JsonProperty("postalCode")
    private java.lang.Integer postalcode;

    public void setPostalcode(java.lang.Integer postalcode) {
        this.postalcode = postalcode;
    }

    public java.lang.Integer getPostalcode() {
        return postalcode;
    }

    @JsonProperty("propertyCategory")
    private java.lang.Integer propertycategory;

    public void setPropertycategory(java.lang.Integer propertycategory) {
        this.propertycategory = propertycategory;
    }

    public java.lang.Integer getPropertycategory() {
        return propertycategory;
    }

    @JsonProperty("@order")
    private java.lang.String order;

    public void setOrder(java.lang.String order) {
        this.order = order;
    }

    public java.lang.String getOrder() {
        return order;
    }

    @JsonProperty("name")
    private java.lang.String name;

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getName() {
        return name;
    }

    @JsonProperty("address2")
    public java.lang.String getAddress2() {
        return address2;
    }

    public void setAddress2(java.lang.String address2) {
        this.address2 = address2;
    }

    private java.lang.String address2;

}