/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class HotelList {

    @JsonProperty("HotelSummary")
    private HotelSummaryElement hotelsummary;

    public HotelSummaryElement getHotelsummary() {
        return hotelsummary;
    }

    public void setHotelsummary(HotelSummaryElement hotelsummary) {
        this.hotelsummary = hotelsummary;
    }

    @JsonProperty("@size")
    private java.lang.String size;

    public void setSize(java.lang.String size) {
        this.size = size;
    }

    public java.lang.String getSize() {
        return size;
    }

    @JsonProperty("@activePropertyCount")
    private java.lang.String activepropertycount;

    public void setActivepropertycount(java.lang.String activepropertycount) {
        this.activepropertycount = activepropertycount;
    }

    public java.lang.String getActivepropertycount() {
        return activepropertycount;
    }

}