/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class NightlyRatesPerRoom {

    @JsonProperty("@size")
    private java.lang.String size;

    public void setSize(java.lang.String size) {
        this.size = size;
    }

    public java.lang.String getSize() {
        return size;
    }

    // @JsonProperty("NightlyRate")
    // private List<NightlyRateElement> nightlyrate;
    //
    // public void setNightlyrate(List<NightlyRateElement> nightlyrate) {
    // this.nightlyrate = nightlyrate;
    // }
    //
    // public List<NightlyRateElement> getNightlyrate() {
    // return nightlyrate;
    // }

}