/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SupplierEANHotelResponse {

    @JsonProperty("HotelListResponse")
    private HotelListResponse hotellistresponse;

    public void setHotellistresponse(HotelListResponse hotellistresponse) {
        this.hotellistresponse = hotellistresponse;
    }

    public HotelListResponse getHotellistresponse() {
        return hotellistresponse;
    }

}