/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Surcharge {

    @JsonProperty("@type")
    private java.lang.String type;

    public void setType(java.lang.String type) {
        this.type = type;
    }

    public java.lang.String getType() {
        return type;
    }

    @JsonProperty("@amount")
    private java.lang.String amount;

    public void setAmount(java.lang.String amount) {
        this.amount = amount;
    }

    public java.lang.String getAmount() {
        return amount;
    }

}