/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.cocha.hotels.model.matesearch.supplier.ean.hotel;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Surcharges {

    @JsonProperty("Surcharge")
    private Surcharge surcharge;

    public void setSurcharge(Surcharge surcharge) {
        this.surcharge = surcharge;
    }

    public Surcharge getSurcharge() {
        return surcharge;
    }

    @JsonProperty("@size")
    private java.lang.String size;

    public void setSize(java.lang.String size) {
        this.size = size;
    }

    public java.lang.String getSize() {
        return size;
    }

}