package https.webservices_sabre_com.websvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-09-30T21:54:46.387-03:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "https://webservices.sabre.com/websvc", name = "ContextChangePortType")
@XmlSeeAlso({org.xmlsoap.schemas.ws._2002._12.secext.ObjectFactory.class, com.sabre.webservices.sabrexml._2011._10.ObjectFactory.class, org.ebxml.namespaces.messageheader.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, com.sabre.services.stl_header.v120.ObjectFactory.class, com.sabre.services.stl.v01.ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContextChangePortType {

    @WebMethod(operationName = "ContextChangeRQ", action = "ContextChangeLLSRQ")
    @WebResult(name = "ContextChangeRS", targetNamespace = "http://webservices.sabre.com/sabreXML/2011/10", partName = "body")
    public com.sabre.webservices.sabrexml._2011._10.ContextChangeRS contextChangeRQ(
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "MessageHeader", targetNamespace = "http://www.ebxml.org/namespaces/messageHeader", header = true)
        javax.xml.ws.Holder<org.ebxml.namespaces.messageheader.MessageHeader> header,
        @WebParam(partName = "header2", mode = WebParam.Mode.INOUT, name = "Security", targetNamespace = "http://schemas.xmlsoap.org/ws/2002/12/secext", header = true)
        javax.xml.ws.Holder<org.xmlsoap.schemas.ws._2002._12.secext.Security> header2,
        @WebParam(partName = "body", name = "ContextChangeRQ", targetNamespace = "http://webservices.sabre.com/sabreXML/2011/10")
        com.sabre.webservices.sabrexml._2011._10.ContextChangeRQ body
    );
}
