package https.webservices_sabre_com.websvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3 2015-10-07T17:44:39.487-03:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "ContextChangeService", wsdlLocation = "file:/home/viken/workspace/meta-search/mate-search/src/main/resources/wsdl/ContextChangeLLS2.0.3RQ.wsdl", targetNamespace = "https://webservices.sabre.com/websvc")
public class ContextChangeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://webservices.sabre.com/websvc", "ContextChangeService");
    public final static QName ContextChangePortType = new QName("https://webservices.sabre.com/websvc",
            "ContextChangePortType");
    static {
        URL url = null;
        try {
            url = new URL(
                    "file:/home/viken/workspace/meta-search/mate-search/src/main/resources/wsdl/ContextChangeLLS2.0.3RQ.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger
                    .getLogger(ContextChangeService.class.getName())
                    .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                            "file:/home/viken/workspace/meta-search/mate-search/src/main/resources/wsdl/ContextChangeLLS2.0.3RQ.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContextChangeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContextChangeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContextChangeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ContextChangeService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContextChangeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContextChangeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns ContextChangePortType
     */
    @WebEndpoint(name = "ContextChangePortType")
    public ContextChangePortType getContextChangePortType() {
        return super.getPort(ContextChangePortType, ContextChangePortType.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns ContextChangePortType
     */
    @WebEndpoint(name = "ContextChangePortType")
    public ContextChangePortType getContextChangePortType(WebServiceFeature... features) {
        return super.getPort(ContextChangePortType, ContextChangePortType.class, features);
    }

}
